version: '3.8'
services:
  app:
    image: dikantek:latest
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your-db-user
      POSTGRES_PASSWORD: your-secure-password
      POSTGRES_DB: your-db-name
    ports:
      - "5432:5432"
